In [61]:
import pandas as pd
import os

In [62]:
os.chdir('C:/Users/basleal/Desktop/tutorial/kaim-week-10')

load data

In [63]:
oil_data=pd.read_csv('data/BrentOilPrices.csv')
wb_gdp=pd.read_csv('data/wb_gdp.csv')
wb_gdp=wb_gdp.rename(columns={'date':'Date '})
wb_gdp

      Unnamed: 0                      country  Date            GDP
0              0  Africa Eastern and Southern   2022  1.191423e+12
1              1  Africa Eastern and Southern   2021  1.085745e+12
2              2  Africa Eastern and Southern   2020  9.333918e+11
3              3  Africa Eastern and Southern   2019  1.009721e+12
4              4  Africa Eastern and Southern   2018  1.012306e+12
...          ...                          ...    ...           ...
9571        9571                     Zimbabwe   1991  8.641482e+09
9572        9572                     Zimbabwe   1990  8.783817e+09
9573        9573                     Zimbabwe   1989  8.286323e+09
9574        9574                     Zimbabwe   1988  7.814784e+09
9575        9575                     Zimbabwe   1987  6.741215e+09

[9576 rows x 4 columns]

In [64]:
wb_gdp=wb_gdp.drop(columns='Unnamed: 0')

In [77]:
print(wb_gdp.columns)
print(oil_data.columns)
wb_gdp.rename(columns={'Date ': 'Date'}, inplace=True)
#oil_data.rename(columns={'Date ': 'Date'}, inplace=True)

Index(['country', 'Date ', 'GDP'], dtype='object')
Index(['Date', 'Price'], dtype='object')

In [78]:
print(wb_gdp.columns)
print(oil_data.columns)

Index(['country', 'Date', 'GDP'], dtype='object')
Index(['Date', 'Price'], dtype='object')

In [73]:
#wb_gdp['Date'] =pd.to_datetime(wb_gdp['Date '])

In [66]:
oil_data['Date'] = pd.to_datetime(oil_data['Date'])
oil_data['Date'] = oil_data['Date'].dt.year

C:\Users\basleal\AppData\Local\Temp\ipykernel_10780\2629081805.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  oil_data['Date'] = pd.to_datetime(oil_data['Date'])

In [50]:
oil_data.rename(columns={'Year': 'Date'}, inplace=True)
wb_gdp.rename(columns={'Year': 'Date'}, inplace=True)

In [12]:
wb_gdp['Year'] = wb_gdp['Date '].dt.year

In [35]:
oil_data.drop(columns='Date',inplace=True)

In [17]:
wb_gdp.drop(columns='Date ',inplace=True)

In [79]:
#oil_data.info()
wb_gdp

                          country  Date           GDP
0     Africa Eastern and Southern  2022  1.191423e+12
1     Africa Eastern and Southern  2021  1.085745e+12
2     Africa Eastern and Southern  2020  9.333918e+11
3     Africa Eastern and Southern  2019  1.009721e+12
4     Africa Eastern and Southern  2018  1.012306e+12
...                           ...   ...           ...
9571                     Zimbabwe  1991  8.641482e+09
9572                     Zimbabwe  1990  8.783817e+09
9573                     Zimbabwe  1989  8.286323e+09
9574                     Zimbabwe  1988  7.814784e+09
9575                     Zimbabwe  1987  6.741215e+09

[9576 rows x 3 columns]

merge data

In [81]:
merged_data=oil_data.merge(wb_gdp,on='Date',how='inner')

In [83]:
merged_data
merged_data.to_csv('merged_data.csv')

Analyze Economic Factors & Oil Prices